(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["about"],{

/***/ "./src/routes/about.svelte":
/*!*********************************!*\
  !*** ./src/routes/about.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/routes/about.svelte generated by Svelte v3.25.0 */


const file = "src/routes/about.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1qxhvvt-style";
	style.textContent = "p.svelte-1qxhvvt{margin:1em auto;font-size:1.2em;text-align:left}section.svelte-1qxhvvt{margin-bottom:1rem}.tldr.svelte-1qxhvvt{font-size:1.3rem;font-weight:700;font-style:italic}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYWJvdXQuc3ZlbHRlIiwic291cmNlcyI6WyJhYm91dC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN0eWxlPlxuICBwIHtcbiAgICBtYXJnaW46IDFlbSBhdXRvO1xuICAgIGZvbnQtc2l6ZTogMS4yZW07XG4gICAgdGV4dC1hbGlnbjogbGVmdDtcbiAgfVxuICBzZWN0aW9uIHtcbiAgICBtYXJnaW4tYm90dG9tOiAxcmVtO1xuICB9XG5cbiAgLnRsZHIge1xuICAgIGZvbnQtc2l6ZTogMS4zcmVtO1xuICAgIGZvbnQtd2VpZ2h0OiA3MDA7XG4gICAgZm9udC1zdHlsZTogaXRhbGljO1xuICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5BYm91dDwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48bWFpbj5cbiAgPHNlY3Rpb24+XG4gICAgPHAgY2xhc3M9XCJ0bGRyXCI+XG4gICAgICBUTDtEUiAtIEknbSBhIFBpdHRzYnVyZ2gtYm9ybiwgZm9ybWVyIGh1bWFuaXRhcmlhbiB3b3JrZXIsIGN1cnJlbnRcbiAgICAgIHNvZnR3YXJlIGVuZ2luZWVyLCBiYXNlZCBpbiBHbGFzZ293LCBlbmpveWluZyBiZWluZyBpbiBvbmUgcGxhY2UgYWZ0ZXIgYVxuICAgICAgbG9uZyBub21hZGljIHBlcmlvZC5cbiAgICA8L3A+XG4gIDwvc2VjdGlvbj5cbiAgPHNlY3Rpb24+XG4gICAgPHA+XG4gICAgICBIZXkgdGhlcmUsIEknbSBKb3NoISBJJ20gYSBHbGFzZ293LWJhc2VkIFNvZnR3YXJlIEVuZ2luZWVyLCBieSB3YXkgb2ZcbiAgICAgIEtlbnlhLCBTb3V0aCBTdWRhbiwgV2FzaGluZ3RvbiBEQywgVGhlIEdhbWJpYSwgYW5kIFBpdHRzYnVyZ2guIEkgYmVjYW1lIGFcbiAgICAgIHByb2dyYW1tZXIgaW4gYSBiaXQgb2YgYSByb3VuZGFib3V0IHdheTogSSBvcmlnaW5hbGx5IHN0dWRpZWQgUHVibGljXG4gICAgICBQb2xpY3kgYW5kIHdhbnRlZCB0byBiZSBhbiB1cmJhbiBwbGFubmVyLCBidXQgdGhlIDIwMDggZmluYW5jaWFsIGNyaXNpc1xuICAgICAgZm9yY2VkIG1lIGludG8gdGhlIGNvbnN1bHRpbmcgd29ybGQsIHdoaWNoIGJvcmVkIG1lIGludG8gYSBkcml2ZSBmb3JcbiAgICAgIGFkdmVudHVyZSBpbiB0aGUgYWlkIGFuZCBkZXZlbG9wbWVudCBzZWN0b3IgYWNyb3NzIHN1Yi1TYWhhcmFuIEFmcmljYS4gTXlcbiAgICAgIHdvcmsgaW5jcmVhc2luZ2x5IHJlcXVpcmVkIHRoZSB1c2Ugb2YgdGVjaG5vbG9naWNhbCB0b29scywgYW5kIElcbiAgICAgIGluY3JlYXNpbmdseSB3YW50ZWQgdG8gYmUgYWJsZSB0byBtYWtlIGFuZCBhZGp1c3QgdGhlIHRvb2xzIG15c2VsZi4gSVxuICAgICAgcGFydGljaXBhdGVkIGluIGEgYm9vdGNhbXAgaW4gTG9uZG9uIGluIDIwMTUsIGFuZCBoYXZlIGJlZW4gYSBzb2Z0d2FyZVxuICAgICAgZW5naW5lZXIgc2luY2UuXG4gICAgPC9wPlxuICAgIDxwPlxuICAgICAgQmVpbmcgYSBTb2Z0d2FyZSBFbmdpbmVlciBzYXRpc2ZpZXMgbXkgZHJpdmUgZm9yIGFsd2F5cyBsZWFybmluZyBuZXdcbiAgICAgIHRoaW5ncy4gV2hpbGUgc3RheWluZyBvbiB0b3Agb2YgbmV3IHRlY2hub2xvZ2llcywgdHJlbmRzLCBhbmQgYmVzdFxuICAgICAgcHJhY3RpY2VzIGlzIGEgY2hhbGxlbmdlLCBpdCdzIGRlZmluaXRlbHkgYSB3ZWxjb21lIG9uZS5cbiAgICA8L3A+XG4gIDwvc2VjdGlvbj5cbiAgPHNlY3Rpb24+XG4gICAgPHA+XG4gICAgICBJIGFtIHByaW1hcmlseSBhIEphdmFTY3JpcHQgZGV2ZWxvcGVyLCB3aXRoIG1vc3Qgb2YgbXkgdGltZSBzcGVudCBvblxuICAgICAgZnJvbnRlbmQgd2ViIGRldmVsb3BtZW50LiBJIGRvIGEgYml0IG9mIGJhY2tlbmQgc3R1ZmYgdG9vLCBhbmQgZXZlbiBzb21lXG4gICAgICBEZXZPcHMsIG1vc3RseSBOb2RlSlMvRXhwcmVzcywgUG9zdGdyZXMsIGFuZCBBV1MuIEZvciB0aGUgcGFzdCB5ZWFyIEkndmVcbiAgICAgIHdyaXR0ZW4gSmF2YVNjcmlwdCBhbG1vc3QgZXhjbHVzaXZlbHkgd2l0aCBUeXBlc2NyaXB0LiBBc2lkZSBmcm9tIFN2ZWx0ZVxuICAgICAgcHJvamVjdHMgd2hlcmUgdGhlcmUgaXMgbm90IGdvb2QgVHlwZXNjcmlwdCBzdXBwb3J0ICh5ZXQpLCBJIHBsYW4gb24gb25seVxuICAgICAgd29ya2luZyBpbiBUeXBlc2NyaXB0IGZyb20gbm93IG9uLlxuICAgIDwvcD5cbiAgICA8cD5cbiAgICAgIE92ZXIgdGhlIHllYXJzIEkndmUgaGFkIHRoZSBwbGVhc3VyZSB0byB3b3JrIHdpdGggb3RoZXIgbGFuZ3VhZ2VzIHRvbztcbiAgICAgIFBIUCwgUnVieSwgSmF2YSwgZXRjLiBJJ20gbm8gZXhwZXJ0IGluIGFueSBvZiB0aGVtLCBidXQgSSBjZXJ0YWlubHkga25vd1xuICAgICAgZW5vdWdoIHRvIG5hdmlnYXRlIGFuIGV4aXN0aW5nIGNvZGUgYmFzZS5cbiAgICA8L3A+XG4gICAgPHA+XG4gICAgICBJIGFtIGN1cnJlbnRseSBsZWFybmluZyBhbmQgcmUtbGVhcm5pbmcgc29tZSBsYW5ndWFnZXMgYW5kIGZyYW1ld29ya3MgdGhhdFxuICAgICAgSSB3cml0ZSBhYm91dCBpbiBteVxuICAgICAgPGEgaHJlZj1cImJsb2dcIj5ibG9nLDwvYT5cbiAgICAgIGluY2x1ZGluZzpcbiAgICA8L3A+XG4gICAgPHVsPlxuICAgICAgPGxpPlJ1c3Q7PC9saT5cbiAgICAgIDxsaT5DU1MtR3JpZCAmIEZsZXhib3g7PC9saT5cbiAgICAgIDxsaT5TdmVsdGU7IGFuZDwvbGk+XG4gICAgICA8bGk+RG9ja2VyLjwvbGk+XG4gICAgPC91bD5cbiAgPC9zZWN0aW9uPlxuICA8c2VjdGlvbj5cbiAgICA8cD5cbiAgICAgIFdoZW4gSSdtIG5vdCB3cml0aW5nIGNvZGUgSSB0cnkgdG8gZ2V0IG91dHNpZGUgYW5kIGVuam95IHRoZSBTY290dGlzaFxuICAgICAgb3V0ZG9vcnMgYXMgbXVjaCBhcyBwb3NzaWJsZS4gSSBsb3ZlIGhpa2luZywgcnVubmluZywgY3ljbGluZywgYW5kXG4gICAgICBmb3JhZ2luZy4gVGhlIHdlYXRoZXIgaGVyZSBpcyBub3QgYWx3YXlzIGNvbmR1Y2l2ZSB0byBvdXRkb29yIGFjdGl2aXRpZXMsXG4gICAgICBzbyB3aGVuIEknbSBzdHVjayBpbnNpZGUgSSBsaWtlIHRvIGNvb2ssIGZlcm1lbnQvcGlja2xlIHdoYXQgSSd2ZSBmb3JhZ2VkLFxuICAgICAgYW5kIHJlYWQsIG1vc3RseSBmaWN0aW9uLiBJIG1pZ2h0IHdyaXRlIGFib3V0IHRoaXMgc3R1ZmYgdG9vIPCfmKwuXG4gICAgPC9wPlxuICA8L3NlY3Rpb24+XG4gIDxzZWN0aW9uPlxuICAgIDxwPlxuICAgICAgSWYgeW91IHdhbnQgdG8gcmVhZCBhYm91dCB3aGF0ZXZlcjsgSmF2YVNjcmlwdCwgUnVzdCwgZmVybWVudGF0aW9uLFxuICAgICAgcnVubmluZywgbGlmZSwgZXRjLiwgcGxlYXNlIGNoZWNrIG91dCBteVxuICAgICAgPGEgaHJlZj1cImJsb2dcIj5ibG9nLjwvYT5cbiAgICA8L3A+XG4gIDwvc2VjdGlvbj5cbjwvbWFpbj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFDRSxDQUFDLGVBQUMsQ0FBQyxBQUNELE1BQU0sQ0FBRSxHQUFHLENBQUMsSUFBSSxDQUNoQixTQUFTLENBQUUsS0FBSyxDQUNoQixVQUFVLENBQUUsSUFBSSxBQUNsQixDQUFDLEFBQ0QsT0FBTyxlQUFDLENBQUMsQUFDUCxhQUFhLENBQUUsSUFBSSxBQUNyQixDQUFDLEFBRUQsS0FBSyxlQUFDLENBQUMsQUFDTCxTQUFTLENBQUUsTUFBTSxDQUNqQixXQUFXLENBQUUsR0FBRyxDQUNoQixVQUFVLENBQUUsTUFBTSxBQUNwQixDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let t0;
	let main;
	let section0;
	let p0;
	let t1;
	let t2;
	let section1;
	let p1;
	let t3;
	let t4;
	let p2;
	let t5;
	let t6;
	let section2;
	let p3;
	let t7;
	let t8;
	let p4;
	let t9;
	let t10;
	let p5;
	let t11;
	let a0;
	let t12;
	let t13;
	let t14;
	let ul;
	let li0;
	let t15;
	let t16;
	let li1;
	let t17;
	let t18;
	let li2;
	let t19;
	let t20;
	let li3;
	let t21;
	let t22;
	let section3;
	let p6;
	let t23;
	let t24;
	let section4;
	let p7;
	let t25;
	let a1;
	let t26;

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("main");
			section0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("TL;DR - I'm a Pittsburgh-born, former humanitarian worker, current\n      software engineer, based in Glasgow, enjoying being in one place after a\n      long nomadic period.");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Hey there, I'm Josh! I'm a Glasgow-based Software Engineer, by way of\n      Kenya, South Sudan, Washington DC, The Gambia, and Pittsburgh. I became a\n      programmer in a bit of a roundabout way: I originally studied Public\n      Policy and wanted to be an urban planner, but the 2008 financial crisis\n      forced me into the consulting world, which bored me into a drive for\n      adventure in the aid and development sector across sub-Saharan Africa. My\n      work increasingly required the use of technological tools, and I\n      increasingly wanted to be able to make and adjust the tools myself. I\n      participated in a bootcamp in London in 2015, and have been a software\n      engineer since.");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Being a Software Engineer satisfies my drive for always learning new\n      things. While staying on top of new technologies, trends, and best\n      practices is a challenge, it's definitely a welcome one.");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I am primarily a JavaScript developer, with most of my time spent on\n      frontend web development. I do a bit of backend stuff too, and even some\n      DevOps, mostly NodeJS/Express, Postgres, and AWS. For the past year I've\n      written JavaScript almost exclusively with Typescript. Aside from Svelte\n      projects where there is not good Typescript support (yet), I plan on only\n      working in Typescript from now on.");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Over the years I've had the pleasure to work with other languages too;\n      PHP, Ruby, Java, etc. I'm no expert in any of them, but I certainly know\n      enough to navigate an existing code base.");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I am currently learning and re-learning some languages and frameworks that\n      I write about in my\n      ");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("blog,");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n      including:");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Rust;");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("CSS-Grid & Flexbox;");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Svelte; and");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Docker.");
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			p6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("When I'm not writing code I try to get outside and enjoy the Scottish\n      outdoors as much as possible. I love hiking, running, cycling, and\n      foraging. The weather here is not always conducive to outdoor activities,\n      so when I'm stuck inside I like to cook, ferment/pickle what I've foraged,\n      and read, mostly fiction. I might write about this stuff too 😬.");
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			p7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("If you want to read about whatever; JavaScript, Rust, fermentation,\n      running, life, etc., please check out my\n      ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("blog.");
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1myew8g\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "MAIN", {});
			var main_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(main);
			section0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "SECTION", { class: true });
			var section0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section0);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section0_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "TL;DR - I'm a Pittsburgh-born, former humanitarian worker, current\n      software engineer, based in Glasgow, enjoying being in one place after a\n      long nomadic period.");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			section1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "SECTION", { class: true });
			var section1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section1);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section1_nodes, "P", { class: true });
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Hey there, I'm Josh! I'm a Glasgow-based Software Engineer, by way of\n      Kenya, South Sudan, Washington DC, The Gambia, and Pittsburgh. I became a\n      programmer in a bit of a roundabout way: I originally studied Public\n      Policy and wanted to be an urban planner, but the 2008 financial crisis\n      forced me into the consulting world, which bored me into a drive for\n      adventure in the aid and development sector across sub-Saharan Africa. My\n      work increasingly required the use of technological tools, and I\n      increasingly wanted to be able to make and adjust the tools myself. I\n      participated in a bootcamp in London in 2015, and have been a software\n      engineer since.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(section1_nodes);
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section1_nodes, "P", { class: true });
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "Being a Software Engineer satisfies my drive for always learning new\n      things. While staying on top of new technologies, trends, and best\n      practices is a challenge, it's definitely a welcome one.");
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			section2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "SECTION", { class: true });
			var section2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section2);
			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section2_nodes, "P", { class: true });
			var p3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p3);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p3_nodes, "I am primarily a JavaScript developer, with most of my time spent on\n      frontend web development. I do a bit of backend stuff too, and even some\n      DevOps, mostly NodeJS/Express, Postgres, and AWS. For the past year I've\n      written JavaScript almost exclusively with Typescript. Aside from Svelte\n      projects where there is not good Typescript support (yet), I plan on only\n      working in Typescript from now on.");
			p3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(section2_nodes);
			p4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section2_nodes, "P", { class: true });
			var p4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p4);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p4_nodes, "Over the years I've had the pleasure to work with other languages too;\n      PHP, Ruby, Java, etc. I'm no expert in any of them, but I certainly know\n      enough to navigate an existing code base.");
			p4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(section2_nodes);
			p5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section2_nodes, "P", { class: true });
			var p5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p5);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p5_nodes, "I am currently learning and re-learning some languages and frameworks that\n      I write about in my\n      ");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p5_nodes, "A", { href: true });
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "blog,");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p5_nodes, "\n      including:");
			p5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(section2_nodes);
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section2_nodes, "UL", {});
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {});
			var li0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li0);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li0_nodes, "Rust;");
			li0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {});
			var li1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li1);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li1_nodes, "CSS-Grid & Flexbox;");
			li1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {});
			var li2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li2);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li2_nodes, "Svelte; and");
			li2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {});
			var li3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li3);
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li3_nodes, "Docker.");
			li3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			section3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "SECTION", { class: true });
			var section3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section3);
			p6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section3_nodes, "P", { class: true });
			var p6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p6);
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p6_nodes, "When I'm not writing code I try to get outside and enjoy the Scottish\n      outdoors as much as possible. I love hiking, running, cycling, and\n      foraging. The weather here is not always conducive to outdoor activities,\n      so when I'm stuck inside I like to cook, ferment/pickle what I've foraged,\n      and read, mostly fiction. I might write about this stuff too 😬.");
			p6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			section4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "SECTION", { class: true });
			var section4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section4);
			p7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section4_nodes, "P", { class: true });
			var p7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p7);
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p7_nodes, "If you want to read about whatever; JavaScript, Rust, fermentation,\n      running, life, etc., please check out my\n      ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p7_nodes, "A", { href: true });
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, "blog.");
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			p7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			main_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "About";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "tldr svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 23, 4, 295);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section0, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section0, file, 22, 2, 281);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p1, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 30, 4, 529);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p2, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 42, 4, 1256);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section1, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section1, file, 29, 2, 515);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p3, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p3, file, 49, 4, 1509);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p4, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p4, file, 57, 4, 1959);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a0, "href", "blog");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 65, 6, 2297);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p5, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p5, file, 62, 4, 2180);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li0, file, 69, 6, 2363);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li1, file, 70, 6, 2384);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li2, file, 71, 6, 2419);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li3, file, 72, 6, 2446);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 68, 4, 2352);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section2, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section2, file, 48, 2, 1495);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p6, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p6, file, 76, 4, 2502);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section3, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section3, file, 75, 2, 2488);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "href", "blog");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 88, 6, 3056);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p7, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p7, file, 85, 4, 2925);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section4, "class", "svelte-1qxhvvt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section4, file, 84, 2, 2911);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(main, file, 21, 0, 272);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, main, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, section0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section0, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, section1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section1, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section1, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, section2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section2, p3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p3, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section2, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section2, p4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p4, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section2, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section2, p5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p5, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p5, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a0, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p5, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section2, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section2, ul);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li0, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li1, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li3, t21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, section3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section3, p6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p6, t23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, section4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section4, p7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p7, t25);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p7, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a1, t26);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(main);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("About", slots, []);
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<About> was created with unknown prop '${key}'`);
	});

	return [];
}

class About extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1qxhvvt-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "About",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (About);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiI2ZmM2MzgwZGIyMTE2ZmMwOWYwOC9hYm91dC5hYm91dC5qcyIsInNvdXJjZXNDb250ZW50IjpbXSwic291cmNlUm9vdCI6IiJ9