(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* src/routes/index.svelte generated by Svelte v3.25.0 */


const { document: document_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];

const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-yac840-style";
	style.textContent = "section.svelte-yac840{margin-bottom:1rem}p.svelte-yac840{margin:1em auto;font-size:1.3em;text-align:left}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IHsgb25Nb3VudCB9IGZyb20gXCJzdmVsdGVcIjtcblxuICBvbk1vdW50KCgpID0+IHtcbiAgICBpZiAod2luZG93Lm5ldGxpZnlJZGVudGl0eSkge1xuICAgICAgd2luZG93Lm5ldGxpZnlJZGVudGl0eS5vbihcImluaXRcIiwgdXNlciA9PiB7XG4gICAgICAgIGlmICghdXNlcikge1xuICAgICAgICAgIHdpbmRvdy5uZXRsaWZ5SWRlbnRpdHkub24oXCJsb2dpblwiLCAoKSA9PiB7XG4gICAgICAgICAgICBkb2N1bWVudC5sb2NhdGlvbi5ocmVmID0gXCIvYWRtaW4vXCI7XG4gICAgICAgICAgfSk7XG4gICAgICAgIH1cbiAgICAgIH0pO1xuICAgIH1cbiAgfSk7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBzZWN0aW9uIHtcbiAgICBtYXJnaW4tYm90dG9tOiAxcmVtO1xuICB9XG5cbiAgcCB7XG4gICAgbWFyZ2luOiAxZW0gYXV0bztcbiAgICBmb250LXNpemU6IDEuM2VtO1xuICAgIHRleHQtYWxpZ246IGxlZnQ7XG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPkpvc2h1YSBTd2lzcydzIFNpdGU8L3RpdGxlPlxuICA8c2NyaXB0IHNyYz1cImh0dHBzOi8vaWRlbnRpdHkubmV0bGlmeS5jb20vdjEvbmV0bGlmeS1pZGVudGl0eS13aWRnZXQuanNcIj5cblxuICA8L3NjcmlwdD5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxtYWluIGlkPVwibWFpblwiPlxuICA8c2VjdGlvbj5cbiAgICA8cD5cbiAgICAgIEhleSB0aGVyZSEgSSdtIEpvc2gsIGEgc29mdHdhcmUgZW5naW5lZXIgYmFzZWQgaW4gR2xhc2dvdy4gVGhpcyBpcyBteSBzaXRlXG4gICAgICB0byBzaG93Y2FzZSBteSBwcm9mZXNzaW9uYWwgc2tpbGx6ICZ0cmFkZTsgYW5kIGJsYXRoZXIgYWJvdXQgd2hhdGV2ZXIgSVxuICAgICAgZmluZCBpbnRlcmVzdGluZywgd2hldGhlciB0aGF0IGJlIGNvZGUgb3IgYW55dGhpbmcgZWxzZS5cbiAgICA8L3A+XG4gIDwvc2VjdGlvbj5cbiAgPHNlY3Rpb24+XG4gICAgPHA+XG4gICAgICBJZiB5b3Ugd2FudCB0byBsZWFybiBtb3JlIGFib3V0IG15IHdvcmsgYW5kIGV4cGVydGlzZSwgcGxlYXNlIGNoZWNrIG91dFxuICAgICAgdGhlXG4gICAgICA8YSBocmVmPVwiYWJvdXRcIj5BYm91dDwvYT5cbiAgICAgIHBhZ2UuIElmIHlvdSB3YW50IHRvIHJlYWQgYWJvdXQgd2hhdGV2ZXI7IEphdmFTY3JpcHQsIFJ1c3QsIGZlcm1lbnRhdGlvbixcbiAgICAgIHJ1bm5pbmcsIGxpZmUsIGV0Yy4sIHBsZWFzZSBjaGVjayBvdXQgbXlcbiAgICAgIDxhIGhyZWY9XCJibG9nXCI+QmxvZzwvYT5cbiAgICAgIC5cbiAgICA8L3A+XG4gIDwvc2VjdGlvbj5cbjwvbWFpbj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFpQkUsT0FBTyxjQUFDLENBQUMsQUFDUCxhQUFhLENBQUUsSUFBSSxBQUNyQixDQUFDLEFBRUQsQ0FBQyxjQUFDLENBQUMsQUFDRCxNQUFNLENBQUUsR0FBRyxDQUFDLElBQUksQ0FDaEIsU0FBUyxDQUFFLEtBQUssQ0FDaEIsVUFBVSxDQUFFLElBQUksQUFDbEIsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document_1.head, style);
}

function create_fragment(ctx) {
	let script;
	let script_src_value;
	let t0;
	let main;
	let section0;
	let p0;
	let t1;
	let t2;
	let section1;
	let p1;
	let t3;
	let a0;
	let t4;
	let t5;
	let a1;
	let t6;
	let t7;

	const block = {
		c: function create() {
			script = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("script");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("main");
			section0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Hey there! I'm Josh, a software engineer based in Glasgow. This is my site\n      to showcase my professional skillz ™ and blather about whatever I\n      find interesting, whether that be code or anything else.");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("If you want to learn more about my work and expertise, please check out\n      the\n      ");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("About");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n      page. If you want to read about whatever; JavaScript, Rust, fermentation,\n      running, life, etc., please check out my\n      ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Blog");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n      .");
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-9i6u4j\"]", document_1.head);
			script = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(head_nodes, "SCRIPT", { src: true });
			var script_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(script);
			script_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "MAIN", { id: true });
			var main_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(main);
			section0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "SECTION", { class: true });
			var section0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section0);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section0_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Hey there! I'm Josh, a software engineer based in Glasgow. This is my site\n      to showcase my professional skillz ™ and blather about whatever I\n      find interesting, whether that be code or anything else.");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			section1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "SECTION", { class: true });
			var section1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section1);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section1_nodes, "P", { class: true });
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "If you want to learn more about my work and expertise, please check out\n      the\n      ");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "A", { href: true });
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "About");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n      page. If you want to read about whatever; JavaScript, Rust, fermentation,\n      running, life, etc., please check out my\n      ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "A", { href: true });
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, "Blog");
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n      .");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			main_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document_1.title = "Joshua Swiss's Site";
			if (script.src !== (script_src_value = "https://identity.netlify.com/v1/netlify-identity-widget.js")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(script, "src", script_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(script, file, 30, 2, 516);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "svelte-yac840");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 37, 4, 652);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section0, "class", "svelte-yac840");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section0, file, 36, 2, 638);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a0, "href", "about");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 47, 6, 1014);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "href", "blog");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 50, 6, 1173);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p1, "class", "svelte-yac840");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 44, 4, 916);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section1, "class", "svelte-yac840");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section1, file, 43, 2, 902);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(main, "id", "main");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(main, file, 35, 0, 619);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document_1.head, script);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, main, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, section0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section0, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, section1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t7);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(script);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(main);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Routes", slots, []);

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(() => {
		if (window.netlifyIdentity) {
			window.netlifyIdentity.on("init", user => {
				if (!user) {
					window.netlifyIdentity.on("login", () => {
						document.location.href = "/admin/";
					});
				}
			});
		}
	});

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Routes> was created with unknown prop '${key}'`);
	});

	$$self.$capture_state = () => ({ onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"] });
	return [];
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document_1.getElementById("svelte-yac840-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7OztBQUNtQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQUVqQyxzREFBTztNQUNELE1BQU0sQ0FBQyxlQUFlO0dBQ3hCLE1BQU0sQ0FBQyxlQUFlLENBQUMsRUFBRSxDQUFDLE1BQU0sRUFBRSxJQUFJO1NBQy9CLElBQUk7S0FDUCxNQUFNLENBQUMsZUFBZSxDQUFDLEVBQUUsQ0FBQyxPQUFPO01BQy9CLFFBQVEsQ0FBQyxRQUFRLENBQUMsSUFBSSxHQUFHLFNBQVMiLCJmaWxlIjoiNmZjNjM4MGRiMjExNmZjMDlmMDgvaW5kZXguaW5kZXguanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSBcInN2ZWx0ZVwiO1xuXG4gIG9uTW91bnQoKCkgPT4ge1xuICAgIGlmICh3aW5kb3cubmV0bGlmeUlkZW50aXR5KSB7XG4gICAgICB3aW5kb3cubmV0bGlmeUlkZW50aXR5Lm9uKFwiaW5pdFwiLCB1c2VyID0+IHtcbiAgICAgICAgaWYgKCF1c2VyKSB7XG4gICAgICAgICAgd2luZG93Lm5ldGxpZnlJZGVudGl0eS5vbihcImxvZ2luXCIsICgpID0+IHtcbiAgICAgICAgICAgIGRvY3VtZW50LmxvY2F0aW9uLmhyZWYgPSBcIi9hZG1pbi9cIjtcbiAgICAgICAgICB9KTtcbiAgICAgICAgfVxuICAgICAgfSk7XG4gICAgfVxuICB9KTtcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIHNlY3Rpb24ge1xuICAgIG1hcmdpbi1ib3R0b206IDFyZW07XG4gIH1cblxuICBwIHtcbiAgICBtYXJnaW46IDFlbSBhdXRvO1xuICAgIGZvbnQtc2l6ZTogMS4zZW07XG4gICAgdGV4dC1hbGlnbjogbGVmdDtcbiAgfVxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+Sm9zaHVhIFN3aXNzJ3MgU2l0ZTwvdGl0bGU+XG4gIDxzY3JpcHQgc3JjPVwiaHR0cHM6Ly9pZGVudGl0eS5uZXRsaWZ5LmNvbS92MS9uZXRsaWZ5LWlkZW50aXR5LXdpZGdldC5qc1wiPlxuXG4gIDwvc2NyaXB0PlxuPC9zdmVsdGU6aGVhZD5cblxuPG1haW4gaWQ9XCJtYWluXCI+XG4gIDxzZWN0aW9uPlxuICAgIDxwPlxuICAgICAgSGV5IHRoZXJlISBJJ20gSm9zaCwgYSBzb2Z0d2FyZSBlbmdpbmVlciBiYXNlZCBpbiBHbGFzZ293LiBUaGlzIGlzIG15IHNpdGVcbiAgICAgIHRvIHNob3djYXNlIG15IHByb2Zlc3Npb25hbCBza2lsbHogJnRyYWRlOyBhbmQgYmxhdGhlciBhYm91dCB3aGF0ZXZlciBJXG4gICAgICBmaW5kIGludGVyZXN0aW5nLCB3aGV0aGVyIHRoYXQgYmUgY29kZSBvciBhbnl0aGluZyBlbHNlLlxuICAgIDwvcD5cbiAgPC9zZWN0aW9uPlxuICA8c2VjdGlvbj5cbiAgICA8cD5cbiAgICAgIElmIHlvdSB3YW50IHRvIGxlYXJuIG1vcmUgYWJvdXQgbXkgd29yayBhbmQgZXhwZXJ0aXNlLCBwbGVhc2UgY2hlY2sgb3V0XG4gICAgICB0aGVcbiAgICAgIDxhIGhyZWY9XCJhYm91dFwiPkFib3V0PC9hPlxuICAgICAgcGFnZS4gSWYgeW91IHdhbnQgdG8gcmVhZCBhYm91dCB3aGF0ZXZlcjsgSmF2YVNjcmlwdCwgUnVzdCwgZmVybWVudGF0aW9uLFxuICAgICAgcnVubmluZywgbGlmZSwgZXRjLiwgcGxlYXNlIGNoZWNrIG91dCBteVxuICAgICAgPGEgaHJlZj1cImJsb2dcIj5CbG9nPC9hPlxuICAgICAgLlxuICAgIDwvcD5cbiAgPC9zZWN0aW9uPlxuPC9tYWluPlxuIl0sInNvdXJjZVJvb3QiOiIifQ==